# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtn_principal.UI'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QWidget)

class Ui_vtn_principal(object):
    def setupUi(self, vtn_principal):
        if not vtn_principal.objectName():
            vtn_principal.setObjectName(u"vtn_principal")
        vtn_principal.resize(540, 519)
        vtn_principal.setMouseTracking(False)
        vtn_principal.setContextMenuPolicy(Qt.DefaultContextMenu)
        vtn_principal.setAcceptDrops(False)
        vtn_principal.setStyleSheet(u"background-color: rgb(170, 170, 255);")
        self.centralwidget = QWidget(vtn_principal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.txt_nombre = QLineEdit(self.centralwidget)
        self.txt_nombre.setObjectName(u"txt_nombre")
        self.txt_nombre.setGeometry(QRect(130, 120, 281, 31))
        self.txt_nombre.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.txt_nombre.setMaxLength(50)
        self.txt_apellido = QLineEdit(self.centralwidget)
        self.txt_apellido.setObjectName(u"txt_apellido")
        self.txt_apellido.setGeometry(QRect(130, 160, 281, 31))
        self.txt_apellido.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.txt_apellido.setMaxLength(50)
        self.lbl_nombre = QLabel(self.centralwidget)
        self.lbl_nombre.setObjectName(u"lbl_nombre")
        self.lbl_nombre.setGeometry(QRect(50, 120, 61, 41))
        font = QFont()
        font.setBold(True)
        self.lbl_nombre.setFont(font)
        self.lbl_apellido = QLabel(self.centralwidget)
        self.lbl_apellido.setObjectName(u"lbl_apellido")
        self.lbl_apellido.setGeometry(QRect(50, 160, 61, 41))
        self.lbl_apellido.setFont(font)
        self.vtn_grabar = QPushButton(self.centralwidget)
        self.vtn_grabar.setObjectName(u"vtn_grabar")
        self.vtn_grabar.setGeometry(QRect(220, 450, 81, 28))
        self.vtn_grabar.setFont(font)
        self.lbl_cedula = QLabel(self.centralwidget)
        self.lbl_cedula.setObjectName(u"lbl_cedula")
        self.lbl_cedula.setGeometry(QRect(50, 210, 71, 21))
        self.lbl_cedula.setFont(font)
        self.lbl_email = QLabel(self.centralwidget)
        self.lbl_email.setObjectName(u"lbl_email")
        self.lbl_email.setGeometry(QRect(50, 240, 81, 31))
        self.lbl_email.setFont(font)
        self.txt_cedula = QLineEdit(self.centralwidget)
        self.txt_cedula.setObjectName(u"txt_cedula")
        self.txt_cedula.setGeometry(QRect(130, 200, 281, 31))
        self.txt_cedula.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.txt_cedula.setMaxLength(10)
        self.txt_email = QLineEdit(self.centralwidget)
        self.txt_email.setObjectName(u"txt_email")
        self.txt_email.setGeometry(QRect(130, 240, 281, 31))
        self.txt_email.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.txt_email.setMaxLength(100)
        self.lbl_tipo_persona = QLabel(self.centralwidget)
        self.lbl_tipo_persona.setObjectName(u"lbl_tipo_persona")
        self.lbl_tipo_persona.setGeometry(QRect(60, 80, 55, 16))
        self.lbl_tipo_persona.setFont(font)
        self.cb_tipo_persona = QComboBox(self.centralwidget)
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.setObjectName(u"cb_tipo_persona")
        self.cb_tipo_persona.setGeometry(QRect(130, 70, 281, 31))
        self.cb_tipo_persona.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lbl_carrera = QLabel(self.centralwidget)
        self.lbl_carrera.setObjectName(u"lbl_carrera")
        self.lbl_carrera.setEnabled(True)
        self.lbl_carrera.setGeometry(QRect(50, 280, 81, 31))
        self.lbl_carrera.setFont(font)
        self.txt_carrera = QLineEdit(self.centralwidget)
        self.txt_carrera.setObjectName(u"txt_carrera")
        self.txt_carrera.setGeometry(QRect(130, 280, 281, 31))
        self.txt_carrera.setAcceptDrops(False)
        self.txt_carrera.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.txt_carrera.setMaxLength(100)
        self.btn_buscar_cedula = QPushButton(self.centralwidget)
        self.btn_buscar_cedula.setObjectName(u"btn_buscar_cedula")
        self.btn_buscar_cedula.setGeometry(QRect(420, 200, 111, 31))
        self.btn_buscar_cedula.setFont(font)
        self.btn_buscar_cedula.setStyleSheet(u"border-color: rgb(7, 8, 72);\n"
"")
        self.lbl_estatura = QLabel(self.centralwidget)
        self.lbl_estatura.setObjectName(u"lbl_estatura")
        self.lbl_estatura.setEnabled(True)
        self.lbl_estatura.setGeometry(QRect(50, 320, 81, 31))
        self.lbl_estatura.setFont(font)
        self.sp_estatura = QSpinBox(self.centralwidget)
        self.sp_estatura.setObjectName(u"sp_estatura")
        self.sp_estatura.setGeometry(QRect(180, 320, 81, 22))
        self.sp_estatura.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.sp_estatura.setMaximum(300)
        self.lbl_f_nacimiento = QLabel(self.centralwidget)
        self.lbl_f_nacimiento.setObjectName(u"lbl_f_nacimiento")
        self.lbl_f_nacimiento.setEnabled(True)
        self.lbl_f_nacimiento.setGeometry(QRect(50, 350, 121, 31))
        self.lbl_f_nacimiento.setFont(font)
        self.date_f_nacimiento = QDateEdit(self.centralwidget)
        self.date_f_nacimiento.setObjectName(u"date_f_nacimiento")
        self.date_f_nacimiento.setGeometry(QRect(180, 360, 81, 22))
        self.date_f_nacimiento.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.date_f_nacimiento.setDateTime(QDateTime(QDate(2000, 1, 1), QTime(0, 0, 0)))
        self.lbl_peso = QLabel(self.centralwidget)
        self.lbl_peso.setObjectName(u"lbl_peso")
        self.lbl_peso.setEnabled(True)
        self.lbl_peso.setGeometry(QRect(50, 390, 111, 31))
        self.lbl_peso.setFont(font)
        self.sp_peso = QSpinBox(self.centralwidget)
        self.sp_peso.setObjectName(u"sp_peso")
        self.sp_peso.setGeometry(QRect(180, 400, 81, 22))
        self.sp_peso.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.sp_peso.setMaximum(200)
        self.vtn_calcular = QPushButton(self.centralwidget)
        self.vtn_calcular.setObjectName(u"vtn_calcular")
        self.vtn_calcular.setGeometry(QRect(290, 360, 81, 28))
        self.vtn_calcular.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(170, 0, 251, 31))
        font1 = QFont()
        font1.setFamilies([u"Comic Sans MS"])
        font1.setPointSize(20)
        font1.setUnderline(False)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"gridline-color: rgb(12, 15, 57);")
        vtn_principal.setCentralWidget(self.centralwidget)
        self.mnb_menu_principal = QMenuBar(vtn_principal)
        self.mnb_menu_principal.setObjectName(u"mnb_menu_principal")
        self.mnb_menu_principal.setGeometry(QRect(0, 0, 540, 21))
        vtn_principal.setMenuBar(self.mnb_menu_principal)
        self.stb_estado = QStatusBar(vtn_principal)
        self.stb_estado.setObjectName(u"stb_estado")
        vtn_principal.setStatusBar(self.stb_estado)

        self.retranslateUi(vtn_principal)

        QMetaObject.connectSlotsByName(vtn_principal)
    # setupUi

    def retranslateUi(self, vtn_principal):
        vtn_principal.setWindowTitle(QCoreApplication.translate("vtn_principal", u"ventana principal", None))
        self.txt_nombre.setText("")
        self.txt_apellido.setText("")
        self.lbl_nombre.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#07084f;\">NOMBRE:</span></p></body></html>", None))
        self.lbl_apellido.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#070848;\">APELLIDO:</span></p></body></html>", None))
        self.vtn_grabar.setText(QCoreApplication.translate("vtn_principal", u"GRABAR", None))
        self.lbl_cedula.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#070848;\">CEDULA:</span></p></body></html>", None))
        self.lbl_email.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#070848;\">EMAIL:</span></p></body></html>", None))
        self.txt_cedula.setText("")
        self.txt_email.setText("")
        self.lbl_tipo_persona.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#0e1255;\">TIPO:</span></p></body></html>", None))
        self.cb_tipo_persona.setItemText(0, QCoreApplication.translate("vtn_principal", u"DOCENTE", None))
        self.cb_tipo_persona.setItemText(1, QCoreApplication.translate("vtn_principal", u"ESTUDIANTE", None))

        self.lbl_carrera.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#070848;\">Carrera:</span></p></body></html>", None))
        self.txt_carrera.setText("")
        self.btn_buscar_cedula.setText(QCoreApplication.translate("vtn_principal", u"Consultar Cedula", None))
        self.lbl_estatura.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#070848;\">Estatura (cm):</span></p></body></html>", None))
        self.lbl_f_nacimiento.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#070848;\">Fecha de nacimiento:</span></p></body></html>", None))
        self.date_f_nacimiento.setDisplayFormat(QCoreApplication.translate("vtn_principal", u"dd/MM/yyyy", None))
        self.lbl_peso.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" color:#070848;\">Peso kg:</span></p></body></html>", None))
        self.vtn_calcular.setText(QCoreApplication.translate("vtn_principal", u"Calcular", None))
        self.label.setText(QCoreApplication.translate("vtn_principal", u"<html><head/><body><p><span style=\" font-weight:600; color:#070848;\">GRUPO # 8</span></p></body></html>", None))
    # retranslateUi

